// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrxfrauybmhmmjjradcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeGZyYXV5Ym1obW1qanJhZGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjc5MzcsImV4cCI6MjA1ODg0MzkzN30.g_7G_2PdNEmOqJkbmgO12W3RHeNsfx6c_FykrE3xhgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);